In [1]:
import random
import utils
import numpy as np
import matplotlib.pyplot as plt

stack_size=10

# LeducGame class definition

In [2]:
class LeducGame:
    deck = []
    actions = [0,1,2] #0 is fold, 1 is check, 2 push
    firstplayer=None; #0 if player1 and 1 if player2
    hand_player1=0;
    hand_player2=0;
    boardcard=0;
    result=0;
    step_number=0
    roundGame=0 #0 preflop, 1 postflop
    game_round=0
    pot=None
    stack1=None
    stack2=None
    lastAction=None
    current_player=None
    game_is_over=None #0 game is not over, #1 game is over
    actions_hist=[]
    #inititate a game
    def __init__(self):
        self.deck = [0,0,1,1,2,2]
        
        #deal card to game from deck
        self.hand_player1=utils.choose_and_remove(self.deck)
        self.hand_player2=utils.choose_and_remove(self.deck)
        self.boardcard=utils.choose_and_remove(self.deck)
        self.result=self.get_result()
        self.firstplayer=random.randrange(0,2)
        #self.firstplayer=0
        self.step_number=0
        self.roundGame=0
        self.game_round=0
        self.pot=0
        self.stack1=stack_size
        self.stack2=stack_size
        self.current_player=self.firstplayer
        self.game_is_over=0 #0 not over, 1 over
        
        self.pot=2
        self.stack1=self.stack1-1
        self.stack2=self.stack2-1
        
    #allow to print leduc game state
    def __str__(self):
        return "FirstPlayer = {} \nHand1 = {} \nHand2 = {} \nBoard = {} \nDeck = {}\nResult = {}\nStack1={}\nStack2={}\nPot={}\nStep={}\nRound={}\nGameIsOver={}\n\n".format(self.firstplayer,self.hand_player1,self.hand_player2,self.boardcard,self.deck, self.result,self.stack1,self.stack2,self.pot,self.step_number,self.game_round,self.game_is_over)
     
    def get_firstplayer(self):
        return self.firstplayer
        
    def get_hand_player1(self):
        return self.hand_player1
    
    def get_hand_player2(self):
        return self.hand_player2
        
    def get_boardcard(self):
        return self.boardcard
        
    def get_current_player(self):
        return self.current_player
        
    def is_game_over(self):
        return self.game_is_over
        
    #result() : 
    # 0  -> draw
    # 1  -> player1 win
    #-1  -> player2 win
    def get_result(self): #determine the best hand
        #Pairs
        if (self.hand_player1==self.boardcard):
            result=1
        elif (self.hand_player2==self.boardcard):
            result=-1
        #Highest card
        elif (self.hand_player1>self.hand_player2):
            result=1
        elif(self.hand_player1<self.hand_player2):
            result=-1
        #Draw
        else:
            result=0
        return result    
    
    def get_allowed_actions(self, action):
        if (action==0):
            return None
        elif (action==1):
            return [0,1,2]
        elif (action==2):
            return [0, 2]
        
    def step_prime(self, action):
        old_round=self.game_round
        gain=0
        
        #QAGENT
        if(self.current_player==0):
            if(action==0):
                gain=-1
                self.game_is_over=1
            elif(action==2):
                self.stack1=0

            #step1
            if(self.step_number==0):
                if(action==1):
                    self.lastAction=1
    
                if(action==2):
                    self.pot=12
                    self.lastAction=2
                self.step_number=1
            #step2        
            elif(self.step_number==1):
                if(action==1):
                    if(self.lastAction==1):
                        if(self.game_round==1):
                            self.game_is_over=1
                            
                            if(self.get_result()==1):
                                gain=1
                            if(self.get_result()==-1):
                                gain=-1
                            
                        self.game_round=1
                        self.step_number=0
                if(action==2):
                    if(self.lastAction==2):
                        self.pot=20
                        self.game_is_over=1
                        
                        if(self.get_result()==1):
                            gain=10
                        if(self.get_result()==-1):
                            gain=-10
                
                            
                    if(self.lastAction==1):
                        self.pot=12
                        self.step_number=2

            #step3
            elif(self.step_number==2):
                if(action==2):
                    self.pot=20
                    self.game_is_over=1
                    
                    if(self.get_result()==1):
                        gain=10
                    if(self.get_result()==-1):
                        gain=-10
                        
        #OPPONENT          
        elif(self.current_player==1):
            if(action==0):
                gain=1
                self.game_is_over=1
            elif(action==2):
                self.stack2=0

            #step1
            if(self.step_number==0):
                if(action==1):
                    self.lastAction=1
                if(action==2):
                    self.pot=12
                    self.lastAction=2
                self.step_number=1
                    
            #step2        
            elif(self.step_number==1):
                if(action==1):
                    if(self.lastAction==1):
                        if(self.game_round==1):
                            self.game_is_over=1
                            
                            if(self.get_result()==1):
                                gain=1
                            if(self.get_result()==-1):
                                gain=-1
                            
                        self.game_round=1
                        self.step_number=0
                if(action==2):
                    if(self.lastAction==2):
                        self.pot=20
                        self.game_is_over=1
                        
                        if(self.get_result()==1):
                            gain=10
                        if(self.get_result()==-1):
                            gain=-10
                            
                    if(self.lastAction==1):
                        self.pot=12
                        self.step_number=2
            #step3
            elif(self.step_number==2):
                if(action==2):
                    self.pot=20
                    self.game_is_over=1
                    
                    if(self.get_result()==1):
                        gain=10
                    if(self.get_result()==-1):
                        gain=-10
            
        allowed_actions= self.get_allowed_actions(action)
        if(old_round==self.game_round):
            if(self.current_player==0):
                self.current_player=1
            elif(self.current_player==1):
                self.current_player=0
            #self.current_player=not(self.current_player)
        else:
            self.current_player=self.firstplayer   
                    
        return gain,self.current_player, allowed_actions          

# Environment

In [3]:
class Environment:
    agent=None
    game=None
    opponent_action=None
    actions_hist=[]
    
    def __init__(self,agent):
        self.game=LeducGame()
        self.agent=agent
        
    def __str__(self):
        return "{} \nOpponent_Action = {}\nStack = {}".format(self.game,self.agent.get_action(),self.stack)
    
    def get_actions_hist(self):
        return self.actions_hist
    
    def get_state(self):
        hand1=self.game.get_hand_player1()
        first=self.game.get_firstplayer()
        boardcard= self.game.get_boardcard()
        
        if self.game.game_round == 0:
            if first is 0:
                return hand1
            elif(first==1 and self.opponent_action==1):
                return hand1+3
            elif(first==1 and self.opponent_action==2):
                return hand1+6
            
        elif self.game.game_round == 1:
            if first is 0:
                if hand1==0:
                    return boardcard+9
                elif hand1== 1:
                    return boardcard+12
                elif hand1== 2:
                    return boardcard+15
            else:
                if (self.opponent_action==1):
                    if hand1==0:
                        return boardcard+18
                    elif hand1==1:
                        return boardcard+21
                    elif hand1==2:
                        return boardcard+24
                if(self.opponent_action==2):
                    if hand1==0:
                        return boardcard+27
                    elif hand1==1:
                        return boardcard+30
                    elif hand1==2:
                        return boardcard+33
    
    def reset(self):
        self.game=LeducGame()
        self.actions_hist=[]
    
    def step(self, qagent_action):
        r=0
        state=None
        self.actions_hist.append([self.get_state(),qagent_action])
        r,current_player,allowed_actions=self.game.step_prime(qagent_action)
        if(allowed_actions==None):
            self.game.game_is_over=1
        if(self.game.is_game_over()==0):
            self.agent.set_action(allowed_actions)
            self.opponent_action=self.agent.get_action()
            #print( "agent action", self.opponent_action)
            r,current_player,allowed_actions= self.game.step_prime(self.opponent_action)
            if(self.game.is_game_over()==1):
                state=None
            else:
                state=self.get_state()
        
        return r, allowed_actions, state
            

## Random Agent

In [4]:
class RandAgent():
    
    action=None
          
        
    def __init__(self):
        #qtable creation
        self.set_action([0,1,2])
        
    def set_action(self,allowed_actions):            
        self.action=random.choice(allowed_actions)
        
    def get_action(self):
        return self.action

## QAgent

In [5]:
class QAgent():
    qtable=[]
 # Agent class definition   state=None
    learning_rate=0.1
    
    state=None #0-5
    gamma=1
    state_number=36
    state=None 
    perf=[]
    
    def __init__(self):
        #qtable creation
        self.qtable=np.zeros((self.state_number,3))
        self.perf=[]
        
    #allow to print leduc game state
    def __str__(self):
        return "State = {} \nQTable = {} \nLearning rate = {}".format(self.state,self.qtable,self.learning_rate)
    
    def explore_action(self, allowed_actions):
        action=random.choice(allowed_actions)
        return action
    
    def exploit_action(self, allowed_actions):
        action=utils.get_max_list(self.qtable[self.state], allowed_actions)
        return action
      
    def set_state(self, state):
        self.state=state    
        
    def set_qtable(self,qtable):
        self.qtable=qtable
        
    def set_perf(self,perf):
        self.perf.append(perf)

    def update(self,reward, actions_hist):
        #print("UPDATE action= {} \n reward = {} \n next_state = {}\n".format(action,reward,next_state))
        new_value = 0

        if(len(actions_hist)==1):
            new_value = (1 - self.learning_rate) * self.qtable[actions_hist[0][0], actions_hist[0][1]] +  self.learning_rate * reward
            self.qtable[actions_hist[0][0], actions_hist[0][1]] = new_value
            #print(actions_hist)
        #if(len(actions_hist)==2):
        #    new_value = (1 - self.learning_rate) * self.qtable[actions_hist[1][0], actions_hist[1][1]] +  self.learning_rate * reward
        #    self.qtable[actions_hist[1][0], actions_hist[1][1]] = new_value

        #    back = (1 - self.learning_rate) * self.qtable[actions_hist[0][0], actions_hist[0][1]] +  self.learning_rate * (0 + self.gamma * reward)
        #    self.qtable[actions_hist[0][0], actions_hist[0][1]] = back

        #if(len(actions_hist)==3):
        #    new_value = (1 - self.learning_rate) * self.qtable[actions_hist[2][0], actions_hist[2][1]] +  self.learning_rate * reward
        #    self.qtable[actions_hist[2][0], actions_hist[2][1]] = new_value

        #    back = (1 - self.learning_rate) * self.qtable[actions_hist[1][0], actions_hist[1][1]] +  self.learning_rate * (0 + self.gamma * reward)
        #    self.qtable[actions_hist[1][0], actions_hist[1][1]] = back

        #    back_prime = (1 - self.learning_rate) * self.qtable[actions_hist[0][0], actions_hist[0][1]] +  self.learning_rate * (0 + self.gamma * reward)
        #    self.qtable[actions_hist[0][0], actions_hist[0][1]] = back_prime

# Training and Testing parameters

In [6]:
epochs_number=1000
evaluate_every=30
test_number=1000

## qAgent vs RandAgent

In [7]:
randAgent=RandAgent()
env=Environment(randAgent)
envTest=Environment(randAgent)
qagent=QAgent()

for i in range(epochs_number):
    allowed_actions=[0,1,2]
    current_player=env.game.get_firstplayer()
    while(env.game.is_game_over()==0):
        state=env.get_state()
        qagent.set_state(state)
        
        if (current_player==1):
            env.agent.set_action(allowed_actions)
            reward,current_player,allowed_actions=env.game.step_prime(env.agent.get_action())
        if(env.game.is_game_over()==0):
            qagent_action=qagent.explore_action(allowed_actions)
            reward,allowed_actions, new_state=env.step(qagent_action)
            qagent.update(reward, env.get_actions_hist())
            qagent.set_state(new_state)
        else:
            env.reset()
            allowed_actions=[0,1,2]
            first_time=True
    
    env.reset()
    
print(qagent.qtable)

[[-0.99637342 -0.21645318  0.89105281]
 [-0.46642144  0.24324718 -1.49731842]
 [-0.8306752  -0.07254853  1.00540049]
 [-0.3439      0.         -1.71      ]
 [-0.26371    -0.01        0.849051  ]
 [-0.19        0.181       1.09      ]
 [-0.79068445  0.01380572 -0.92306033]
 [-0.79688489 -0.0663659  -0.11009446]
 [-0.84366338  0.059049    2.53814688]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.        

In [8]:
qagent.qtable[0][2]

0.8910528137802414

In [9]:
game=LeducGame()
game.step_prime(1)
print(game)
game.step_prime(2)
print(game)
game.step_prime(2)
print(game)

FirstPlayer = 1 
Hand1 = 2 
Hand2 = 1 
Board = 1 
Deck = [0, 0, 2]
Result = -1
Stack1=9
Stack2=9
Pot=2
Step=1
Round=0
GameIsOver=0


FirstPlayer = 1 
Hand1 = 2 
Hand2 = 1 
Board = 1 
Deck = [0, 0, 2]
Result = -1
Stack1=0
Stack2=9
Pot=12
Step=2
Round=0
GameIsOver=0


FirstPlayer = 1 
Hand1 = 2 
Hand2 = 1 
Board = 1 
Deck = [0, 0, 2]
Result = -1
Stack1=0
Stack2=0
Pot=20
Step=2
Round=0
GameIsOver=1


