In [1]:
import numpy as np


class QN_Agent(object):
    ''' A Q-learning agent.
    '''

    def __init__(self, action_num):
        ''' Initilize the random agent
        Args:
            action_num (int): The size of the ouput action space
        '''
        self.use_raw = False
        self.action_num = action_num
        self.q_table=np.random.uniform(low=-1, high=1, size=([3]*2+[14]*2+[4]))

    @staticmethod
    def step(state):
        print("coucou")
        ''' Predict the action given the curent state in gerenerating training data.
        Args:
            state (dict): An dictionary that represents the current state
        Returns:
            action (int): The action predicted (randomly chosen) by the random agent
        '''
        #return np.random.randint(0, self.action_num)
        return np.random.choice(state['legal_actions'])

    def eval_step(self, state):
        ''' Predict the action given the curent state for evaluation.
            Since the random agents are not trained. This function is equivalent to step function
        Args:
            state (dict): An dictionary that represents the current state
        Returns:
            action (int): The action predicted (randomly chosen) by the random agent
            probs (list): The list of action probabilities
        '''
        old_q_value=-1000
        probs = [0 for _ in range(self.action_num)]    
        for i in state['legal_actions']:
            new_q_value=q_table[state][i]
            if old_q_value < new_q_value:
                old_q_value= new_q_value
                best_action=i
            probs[i] = 1/len(state['legal_actions'])
        
        
        return best_action, probs

In [2]:
test =[3]*2+[14]*2+[4]
print(test)
q_table=np.random.uniform(low=-1, high=1, size=(test))
print(q_table)

[3, 3, 14, 14, 4]
[[[[[ 3.75417498e-02  4.79971498e-01 -5.69782061e-01  3.08400485e-01]
    [-7.56876094e-01  8.78295374e-01 -9.16920674e-01 -5.82570275e-01]
    [-4.70155089e-01 -9.46885203e-01  4.54565220e-01  8.32549782e-01]
    ...
    [-5.76888586e-01  3.80735574e-01  7.61626629e-01 -7.36085602e-01]
    [-6.06529555e-01  7.96565799e-01  8.87543507e-01  1.57681360e-01]
    [-5.03193370e-01 -5.24496205e-01  2.06344413e-01 -6.40886506e-01]]

   [[-8.31724298e-01 -2.61351932e-01 -4.83471632e-01 -4.18917243e-01]
    [ 7.95430240e-01  7.99732913e-01  7.04579384e-01 -2.58863175e-01]
    [ 2.91452122e-01  2.26479835e-02 -1.01516702e-01  3.43724297e-01]
    ...
    [ 7.80252803e-01 -9.94706311e-02 -2.01895886e-01 -2.74619148e-01]
    [-4.91284697e-01 -7.26378666e-01  5.57545598e-01 -2.90212483e-01]
    [ 6.16253010e-01 -7.05394988e-01 -5.23787047e-01 -4.05889420e-01]]

   [[ 9.87535316e-02 -7.11295301e-01 -6.58334137e-01  1.42364051e-01]
    [ 6.38811227e-02  7.24895303e-01  3.88809146e-01

In [3]:
import numpy as np

import rlcard
from rlcard.agents.best_response_agent import BRAgent
from rlcard.agents.random_agent import RandomAgent
from rlcard.agents.cfr_agent import CFRAgent
from rlcard.agents.cfr_agent import CFRAgent
from rlcard import models
from rlcard.utils.utils import set_global_seed, tournament
from rlcard.utils.logger import Logger

# Make environment and enable human mode
env = rlcard.make('leduc-holdem', config={'allow_step_back': True, 'allow_raw_data': True})
eval_env = rlcard.make('leduc-holdem', config={'allow_step_back': True, 'allow_raw_data': True})

# Set the iterations numbers and how frequently we evaluate/save plot
evaluate_every = 100
save_plot_every = 1000
evaluate_num = 10000
episode_num = 10000000

# The paths for saving the logs and learning curves
log_dir = './experiments/leduc_holdem_br_result/'

# Set a global seed
set_global_seed(0)


# Initilize CFR Agent
#opponent = CFRAgent(env) 
opponent = RandomAgent(action_num=env.action_num)
#opponent.load()  # If we have saved model, we first load the model

#agent = RandomAgent(action_num=env.action_num)
#agent = BRAgent(eval_env, opponent)
#agent = CFRAgent(env) 
agent = QN_Agent(action_num=env.action_num) 

eval_env.set_agents([agent, opponent])
# Init a Logger to plot the learning curve
logger = Logger(log_dir)

for episode in range(episode_num):
    #opponent.train()
    #agent.train()
    print('\rIteration {}'.format(episode), end='')
    # Evaluate the performance. Play with NFSP agents.
    if episode % evaluate_every == 0:
        logger.log_performance(env.timestep, tournament(eval_env, evaluate_num)[0])

# Close files in the logger
logger.close_files()
logger.plot('BR')

Iteration 0

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices