In [1]:
import numpy as np


class QN_Agent(object):
    ''' A Q-learning agent.
    '''

    def __init__(self, action_num):
        ''' Initilize the random agent
        Args:
            action_num (int): The size of the ouput action space
        '''
        self.use_raw = False
        self.action_num = action_num
        self.q_table=np.random.uniform(low=-1, high=1, size=([3]*2+[14]*2+[4]))

    @staticmethod
    def step(state):
        print("coucou")
        ''' Predict the action given the curent state in gerenerating training data.
        Args:
            state (dict): An dictionary that represents the current state
        Returns:
            action (int): The action predicted (randomly chosen) by the random agent
        '''
        #return np.random.randint(0, self.action_num)
        return np.random.choice(state['legal_actions'])

    def eval_step(self, state):
        ''' Predict the action given the curent state for evaluation.
            Since the random agents are not trained. This function is equivalent to step function
        Args:
            state (dict): An dictionary that represents the current state
        Returns:
            action (int): The action predicted (randomly chosen) by the random agent
            probs (list): The list of action probabilities
        '''
        old_q_value=-1000
        probs = [0 for _ in range(self.action_num)]    
        for i in state['legal_actions']:
            new_q_value=q_table[state][i]
            if old_q_value < new_q_value:
                old_q_value= new_q_value
                best_action=i
            probs[i] = 1/len(state['legal_actions'])
        
        
        return best_action, probs

In [2]:
test =[3]*2+[14]*2+[4]
print(test)
q_table=np.random.uniform(low=-1, high=1, size=(test))
print(q_table)

[3, 3, 14, 14, 4]
[[[[[-3.29611371e-01  7.86904502e-01  7.10416763e-01 -1.80316709e-02]
    [ 1.08590921e-02 -9.63984279e-02  9.48413120e-01 -1.38983419e-01]
    [-5.24224924e-01  9.39232872e-01 -4.65900564e-01  9.14441887e-01]
    ...
    [ 8.42923951e-01 -1.76248469e-01 -4.07005304e-01  3.29359260e-01]
    [-4.89705120e-01  9.23420646e-01  4.98761299e-02 -5.47328108e-01]
    [ 5.81417480e-01 -1.42984131e-01 -9.65368122e-01  7.66594893e-01]]

   [[ 6.11612903e-01 -4.83590287e-01  8.43651906e-01 -5.91322358e-02]
    [ 5.94582419e-01 -3.69532234e-02  1.94584215e-01 -5.69187704e-01]
    [ 3.89237924e-01 -2.35942018e-01 -8.11333150e-01  3.21132528e-01]
    ...
    [ 3.83455581e-01 -4.62105335e-01  9.21286831e-01 -9.24824789e-01]
    [ 2.63174464e-01  5.69101830e-01 -6.06553500e-01 -5.69411147e-02]
    [-8.43873579e-02  8.26612788e-01 -8.87410986e-01  7.41526305e-01]]

   [[ 6.52850752e-02  8.36899315e-01 -4.91865924e-01 -6.95076485e-01]
    [ 4.71655878e-01  1.17867232e-01 -1.14222525e-01

In [3]:
import numpy as np

import rlcard
from rlcard.agents.best_response_agent import BRAgent
from rlcard.agents.random_agent import RandomAgent
from rlcard.agents.cfr_agent import CFRAgent
from rlcard.agents.cfr_agent import CFRAgent
from rlcard import models
from rlcard.utils.utils import set_global_seed, tournament
from rlcard.utils.logger import Logger

# Make environment and enable human mode
env = rlcard.make('leduc-holdem', config={'allow_step_back': True, 'allow_raw_data': True})
eval_env = rlcard.make('leduc-holdem', config={'allow_step_back': True, 'allow_raw_data': True})

# Set the iterations numbers and how frequently we evaluate/save plot
evaluate_every = 100
save_plot_every = 1000
evaluate_num = 10000
episode_num = 10000000

# The paths for saving the logs and learning curves
log_dir = './experiments/leduc_holdem_br_result/'

# Set a global seed
set_global_seed(0)


# Initilize CFR Agent
#opponent = CFRAgent(env) 
opponent = RandomAgent(action_num=env.action_num)
#opponent.load()  # If we have saved model, we first load the model

#agent = RandomAgent(action_num=env.action_num)
#agent = BRAgent(eval_env, opponent)
#agent = CFRAgent(env) 
agent = QN_Agent(env) 

eval_env.set_agents([agent, opponent])
# Init a Logger to plot the learning curve
logger = Logger(log_dir)

for episode in range(episode_num):
    #opponent.train()
    #agent.train()
    print('\rIteration {}'.format(episode), end='')
    # Evaluate the performance. Play with NFSP agents.
    if episode % evaluate_every == 0:
        logger.log_performance(env.timestep, tournament(eval_env, evaluate_num)[0])

# Close files in the logger
logger.close_files()
logger.plot('BR')

Iteration 0

TypeError: 'LeducholdemEnv' object cannot be interpreted as an integer