In [4]:
import random
import utils
import numpy as np
import matplotlib.pyplot as plt
from Game.LeducGame import *
from Environment.Environment import *
from Opponent_agent.RandAgent import *
from Opponent_agent.GreedyAgent import *
from Opponent_agent.HumanAgent import *
from Qagent.QAgent import *
import pandas as pd
import seaborn as sns

stack_size=10
random_agent_qtable=None
greedy_agent_qtable=None

# Training and Testing parameters

In [5]:
epochs_number=500000
evaluate_every=50
test_number=10000

## qAgent vs RandAgent

In [3]:
randAgent=RandAgent()
env=Environment(randAgent)
envTest=Environment(randAgent)
qagent=QAgent()


for i in range(epochs_number):

    #TEST
    if(i % evaluate_every == 0):
        perf=0
        for j in range(test_number):
            envTest.reset()
            current_player=envTest.game.get_firstplayer()
            allowed_actions=[0,1,2]
            if(current_player==1):
                envTest.agent.set_action(allowed_actions,None,envTest.game.get_game_round(), envTest.game.get_hand_player2(),envTest.game.get_boardcard())
                envTest.set_opponent_action(envTest.agent.get_action())
                reward,current_player,allowed_actions=envTest.game.step_prime(envTest.agent.get_action())
                

            while(envTest.game.is_game_over()==0):
                state=envTest.get_state()
                qagent.set_state(state)
                qagent_action=qagent.exploit_action(allowed_actions)
                reward,allowed_actions, new_state=envTest.step(qagent_action)

            if(envTest.game.is_game_over()==1):
                perf=perf+reward
        qagent.set_perf(float(perf)/test_number)    
    
    #TRAIN
    current_player=env.game.get_firstplayer()
    allowed_actions=[0,1,2]
    if(current_player==1):
        env.agent.set_action(allowed_actions,0,0,0,0)
        env.set_opponent_action(env.agent.get_action())
        reward,current_player,allowed_actions=env.game.step_prime(env.agent.get_action())

    while(env.game.is_game_over()==0):
        state=env.get_state()
        qagent.set_state(state)
        qagent_action=qagent.explore_action(allowed_actions)
        reward,allowed_actions, new_state=env.step(qagent_action)

        if(env.game.is_game_over()==1):
            qagent.update(reward, env.get_actions_hist())
    
    env.reset()
    state=env.get_state()
    qagent.set_state(state)

with np.printoptions(precision=3, suppress=True):
    print(qagent.qtable)
random_agent_qtable=qagent.qtable

KeyboardInterrupt: 

In [6]:
randAgent=RandAgent()
env=Environment(randAgent)
envTest=Environment(randAgent)
qagent=QAgent()


for i in range(epochs_number):    
    #TRAIN
    current_player=env.game.get_firstplayer()
    allowed_actions=[0,1,2]
    if(current_player==1):
        env.agent.set_action(allowed_actions,0,0,0,0)
        env.set_opponent_action(env.agent.get_action())
        reward,current_player,allowed_actions=env.game.step_prime(env.agent.get_action())

    while(env.game.is_game_over()==0):
        state=env.get_state()
        qagent.set_state(state)
        qagent_action=qagent.explore_action(allowed_actions)
        reward,allowed_actions, new_state=env.step(qagent_action)

        if(env.game.is_game_over()==1):
            qagent.update(reward, env.get_actions_hist())
    
    env.reset()
    state=env.get_state()
    qagent.set_state(state)

with np.printoptions(precision=3, suppress=True):
    print(qagent.qtable)
random_agent_qtable=qagent.qtable

[[-1.     8.698 -1.76 ]
 [-1.     8.577  2.532]
 [-1.     5.803  2.843]
 [-1.     6.419 -0.217]
 [-1.     7.905 -0.161]
 [-1.     6.359  1.442]
 [-1.     0.    -4.168]
 [-1.     0.     0.256]
 [-1.     0.     4.742]
 [-1.     3.129  7.069]
 [-1.     3.911 -4.689]
 [-1.     2.553 -3.481]
 [-1.     2.633 -3.572]
 [-1.     3.477  4.399]
 [-1.     3.881  1.625]
 [-1.     3.172  2.352]
 [-1.     3.134  0.123]
 [-1.     3.819  6.288]
 [-1.     1.     5.021]
 [-1.    -0.957 -2.986]
 [-1.    -0.865 -2.505]
 [-1.    -0.755 -2.251]
 [-1.     1.     5.767]
 [-1.     0.15   2.285]
 [-1.     0.377  2.736]
 [-1.     0.318 -0.695]
 [-1.     1.     5.018]
 [-1.     0.    10.   ]
 [-1.     0.    -6.753]
 [-1.     0.    -5.688]
 [-1.     0.    -6.72 ]
 [-1.     0.    10.   ]
 [-1.     0.     2.846]
 [-1.     0.     2.883]
 [-1.     0.     0.895]
 [-1.     0.    10.   ]]


In [ ]:
plt.plot(qagent.perf)

In [7]:
df = pd.DataFrame(qagent.qtable, columns=['fold', "check","push"])

cm = sns.light_palette('blue', as_cmap=True)

s = df.style.background_gradient(cmap=cm, low=0, high=1, axis=1)
s

## qAgent vs GreedyAgent

In [ ]:
greedy=GreedyAgent()
env=Environment(greedy)
envTest=Environment(greedy)
qagent=QAgent()


for i in range(epochs_number):

    #TEST
    if(i % evaluate_every == 0):
        perf=0
        for j in range(test_number):
            envTest.reset()
            current_player=envTest.game.get_firstplayer()
            allowed_actions=[0,1,2]
            if(current_player==1):
                envTest.agent.set_action(allowed_actions,None,envTest.game.get_game_round(), envTest.game.get_hand_player2(),envTest.game.get_boardcard())
                envTest.set_opponent_action(envTest.agent.get_action())
                reward,current_player,allowed_actions=envTest.game.step_prime(envTest.agent.get_action())

            while(envTest.game.is_game_over()==0):
                state=envTest.get_state()
                qagent.set_state(state)
                qagent_action=qagent.exploit_action(allowed_actions)
                reward,allowed_actions, new_state=envTest.step(qagent_action)

            if(envTest.game.is_game_over()==1):
                perf=perf+reward
        qagent.set_perf(float(perf)/test_number)    
    
    #TRAIN
    current_player=env.game.get_firstplayer()
    allowed_actions=[0,1,2]
    if(current_player==1):
        env.agent.set_action(allowed_actions,None,env.game.get_game_round(), env.game.get_hand_player2(),env.game.get_boardcard())
        env.set_opponent_action(env.agent.get_action())
        reward,current_player,allowed_actions=env.game.step_prime(env.agent.get_action())

    while(env.game.is_game_over()==0):
        state=env.get_state()
        qagent.set_state(state)
        qagent_action=qagent.explore_action(allowed_actions)
        reward,allowed_actions, new_state=env.step(qagent_action)

        if(env.game.is_game_over()==1):
            qagent.update(reward, env.get_actions_hist())
    
    env.reset()
    state=env.get_state()
    qagent.set_state(state)

with np.printoptions(precision=3, suppress=True):
    print(qagent.qtable)
random_agent_qtable=qagent.qtable

In [8]:
greedy=GreedyAgent()
env=Environment(greedy)
envTest=Environment(greedy)
qagent=QAgent()


for i in range(epochs_number): 
    
    #TRAIN
    current_player=env.game.get_firstplayer()
    allowed_actions=[0,1,2]
    if(current_player==1):
        env.agent.set_action(allowed_actions,None,env.game.get_game_round(), env.game.get_hand_player2(),env.game.get_boardcard())
        env.set_opponent_action(env.agent.get_action())
        reward,current_player,allowed_actions=env.game.step_prime(env.agent.get_action())

    while(env.game.is_game_over()==0):
        state=env.get_state()
        qagent.set_state(state)
        qagent_action=qagent.explore_action(allowed_actions)
        reward,allowed_actions, new_state=env.step(qagent_action)

        if(env.game.is_game_over()==1):
            qagent.update(reward, env.get_actions_hist())
    
    env.reset()
    state=env.get_state()
    qagent.set_state(state)

with np.printoptions(precision=3, suppress=True):
    print(qagent.qtable)
random_agent_qtable=qagent.qtable

[[ -1.      9.328  -1.539]
 [ -1.      8.546  -2.852]
 [ -1.      9.226   1.547]
 [ -1.      9.159  -2.035]
 [ -1.      7.919  -0.454]
 [ -1.      9.204   1.153]
 [ -1.      0.     -4.753]
 [ -1.      0.     -5.178]
 [ -1.      0.      1.685]
 [ -1.      1.88    2.28 ]
 [ -1.      4.372  -2.754]
 [ -1.      3.146  -0.569]
 [ -1.      2.442  -5.223]
 [ -1.      2.203   3.075]
 [ -1.      2.059  -1.523]
 [ -1.      3.656  -0.289]
 [ -1.      3.183  -1.539]
 [ -1.      1.      1.   ]
 [ -1.      1.      1.863]
 [ -1.     -0.6     0.309]
 [ -1.     -0.78    1.   ]
 [ -1.     -0.805  -1.786]
 [ -1.      1.      1.689]
 [ -1.      0.702   1.   ]
 [ -1.      0.725   0.774]
 [ -1.      0.325   0.121]
 [ -1.      1.      1.   ]
 [ -1.      0.     10.   ]
 [ -1.      0.    -10.   ]
 [ -1.      0.    -10.   ]
 [ -1.      0.     -8.913]
 [ -1.      0.     10.   ]
 [ -1.      0.     -8.838]
 [ -1.      0.     -1.088]
 [ -1.      0.     -7.842]
 [ -1.      0.     10.   ]]


In [ ]:
plt.plot(qagent.perf)

In [9]:
df = pd.DataFrame(qagent.qtable, columns=['fold', "check","push"])

cm = sns.light_palette('blue', as_cmap=True)

s = df.style.background_gradient(cmap=cm, low=0, high=1, axis=1)
s

## qAgent (trained with a random agent) vs HumanAgent

In [ ]:
humanAgent=HumanAgent()
env=Environment(humanAgent)
qagent=QAgent()
qagent.set_qtable(random_agent_qtable)

print("How to play?\n\nFor the actions:\n\t- 0 : Fold\n\t- 1 : Check\n\t- 2 : Push\n\nFor the cards:\n\t- 0 : Jack\n\t- 1 : Queen\n\t- 2 : King\n\n ")
for i in range(1):
    allowed_actions=[0,1,2]
    current_player=env.game.get_firstplayer()
    while(env.game.is_game_over()==0):
        state=env.get_state()
        qagent.set_state(state)
        
        if (current_player==1):
            env.agent.set_action(allowed_actions,None, env.game.get_game_round(), env.game.get_hand_player2(),env.game.get_boardcard())
            env.set_opponent_action(env.agent.get_action())
            reward,current_player,allowed_actions=env.game.step_prime(env.agent.get_action())
            if(env.game.is_game_over()==1):
                print("You loose!! He has a:", env.game.get_hand_player1(), "\n\n")
        if(env.game.is_game_over()==0):
            state=env.get_state()
            qagent.set_state(state)
            qagent_action=qagent.exploit_action(allowed_actions)
            reward,allowed_actions, new_state=env.step(qagent_action)
            if(env.game.is_game_over()==1):
                if(reward<0):
                    print("His action was: ", qagent_action, "\nHe has a: ",env.game.get_hand_player1(), "\nCongratulation, you win !!!\n\n" )
                elif(reward>0):
                    print("His action was: ", qagent_action, "\nHe has a: ",env.game.get_hand_player1(), "\nSorry, you loose !!!\n\n" )
                elif(reward==0):
                    print("His action was: ", qagent_action, "\nHe has a: ",env.game.get_hand_player1(), "\nIt's a draw !!!\n\n" )
                qagent.update(reward, env.get_actions_hist())
            qagent.set_state(new_state)

    
    env.reset()
    

## qAgent (trained with a greedy agent) vs HumanAgent

In [ ]:
humanAgent=HumanAgent()
env=Environment(humanAgent)
qagent=QAgent()
qagent.set_qtable(greedy_agent_qtable)

    
print("How to play?\n\nFor the actions:\n\t- 0 : Fold\n\t- 1 : Check\n\t- 2 : Push\n\nFor the cards:\n\t- 0 : Jack\n\t- 1 : Queen\n\t- 2 : King\n\n ")
for i in range(1):
    allowed_actions=[0,1,2]
    current_player=env.game.get_firstplayer()
    while(env.game.is_game_over()==0):
        state=env.get_state()
        qagent.set_state(state)
        
        if (current_player==1):
            env.agent.set_action(allowed_actions,None, env.game.get_game_round(), env.game.get_hand_player2(),env.game.get_boardcard())
            env.set_opponent_action(env.agent.get_action())
            reward,current_player,allowed_actions=env.game.step_prime(env.agent.get_action())
            if(env.game.is_game_over()==1):
                print("You loose!! He has a:", env.game.get_hand_player1(), "\n\n")
        if(env.game.is_game_over()==0):
            state=env.get_state()
            qagent.set_state(state)
            qagent_action=qagent.exploit_action(allowed_actions)
            reward,allowed_actions, new_state=env.step(qagent_action)
            if(env.game.is_game_over()==1):
                if(reward<0):
                    print("His action was: ", qagent_action, "\nHe has a: ",env.game.get_hand_player1(), "\nCongratulation, you win !!!\n\n" )
                elif(reward>0):
                    print("His action was: ", qagent_action, "\nHe has a: ",env.game.get_hand_player1(), "\nSorry, you loose !!!\n\n" )
                elif(reward==0):
                    print("His action was: ", qagent_action, "\nHe has a: ",env.game.get_hand_player1(), "\nIt's a draw !!!\n\n" )
                qagent.update(reward, env.get_actions_hist())
            qagent.set_state(new_state)

    
    env.reset()
    

In [ ]:
game = LeducGame()
print(game)
game.step_prime(1)
print(game)
game.step_prime(1)
print(game)
game.step_prime(1)
print(game)
game.step_prime(2)
print(game)
game.step_prime(2)
print(game)

In [ ]:
greedy=GreedyAgent()
env=Environment(greedy)
envTest=Environment(greedy)
qagent=QAgent()
update=0
update_every=100
diff=[]
converge=0
for i in range(epochs_number):

    #TRAIN
    current_player=env.game.get_firstplayer()
    allowed_actions=[0,1,2]
    if(current_player==1):
        env.agent.set_action(allowed_actions,None,env.game.get_game_round(), env.game.get_hand_player2(),env.game.get_boardcard())
        env.set_opponent_action(env.agent.get_action())
        reward,current_player,allowed_actions=env.game.step_prime(env.agent.get_action())

    while(env.game.is_game_over()==0):
        state=env.get_state()
        qagent.set_state(state)
        qagent_action=qagent.explore_action(allowed_actions)
        reward,allowed_actions, new_state=env.step(qagent_action)

        if(env.game.is_game_over()==1):
            if(update%update_every==0):
                diff= np.multiply(np.subtract(qagent.qtable, old_qtable),np.subtract(qagent.qtable, old_qtable))
                #print("diff: ", diff)
                #diff= np.subtract(qagent.qtable, old_qtable) * np.subtract(qagent.qtable, old_qtable)
                print("old : ", old_qtable)
                print("new : ", qagent.qtable)
                difference_array = np.subtract(qagent.qtable, old_qtable)
                print("diff: ", difference_array)
                squared_array = np.square(difference_array)
                mse = squared_array.mean()
                #diff= ((qagent.qtable-old_qtable)**2).sum()
                #converge=np.sum(diff)
                #qagent.set_perf(converge/(36*3))
                qagent.set_perf(mse)
                old_qtable=qagent.qtable
                
            qagent.update(reward, env.get_actions_hist())
            update=update+1
    
    env.reset()
    state=env.get_state()
    qagent.set_state(state)

with np.printoptions(precision=3, suppress=True):
    print(qagent.qtable)
random_agent_qtable=qagent.qtable